[package]
name = "dr4m-client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = {path = "../common"}
logger = {path = "../logger"}
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
futures = "0.3"
url = "2"
crossterm = { version = "0.29", features = ["event-stream"] }
ratatui = "0.30.0"
